# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.proc_desc = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proc_desc.sizePolicy().hasHeightForWidth())
        self.proc_desc.setSizePolicy(sizePolicy)
        self.proc_desc.setObjectName("proc_desc")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.proc_desc)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pid_input = QtWidgets.QLineEdit(self.proc_desc)
        self.pid_input.setObjectName("pid_input")
        self.verticalLayout.addWidget(self.pid_input)
        self.groupBox = QtWidgets.QGroupBox(self.proc_desc)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_capa = QtWidgets.QPushButton(self.groupBox)
        self.button_capa.setObjectName("button_capa")
        self.horizontalLayout_2.addWidget(self.button_capa)
        self.button_pe = QtWidgets.QPushButton(self.groupBox)
        self.button_pe.setObjectName("button_pe")
        self.horizontalLayout_2.addWidget(self.button_pe)
        self.button_memeory = QtWidgets.QPushButton(self.groupBox)
        self.button_memeory.setObjectName("button_memeory")
        self.horizontalLayout_2.addWidget(self.button_memeory)
        self.button_packer = QtWidgets.QPushButton(self.groupBox)
        self.button_packer.setObjectName("button_packer")
        self.horizontalLayout_2.addWidget(self.button_packer)
        self.verticalLayout.addWidget(self.groupBox)
        self.desc_text = QtWidgets.QTextBrowser(self.proc_desc)
        self.desc_text.setObjectName("desc_text")
        self.verticalLayout.addWidget(self.desc_text)
        self.horizontalLayout.addWidget(self.proc_desc)
        self.proc_table = QtWidgets.QGroupBox(self.centralwidget)
        self.proc_table.setObjectName("proc_table")
        self.gridLayout = QtWidgets.QGridLayout(self.proc_table)
        self.gridLayout.setObjectName("gridLayout")
        self.table_view = QtWidgets.QTableView(self.proc_table)
        self.table_view.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_view.setLineWidth(1)
        self.table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_view.setObjectName("table_view")
        self.table_view.horizontalHeader().setDefaultSectionSize(100)
        self.table_view.horizontalHeader().setMinimumSectionSize(50)
        self.gridLayout.addWidget(self.table_view, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.proc_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.proc_desc.setTitle(_translate("MainWindow", "Proc Description"))
        self.button_capa.setText(_translate("MainWindow", "CAPA"))
        self.button_pe.setText(_translate("MainWindow", "PE"))
        self.button_memeory.setText(_translate("MainWindow", "Memory"))
        self.button_packer.setText(_translate("MainWindow", "Packer"))
        self.desc_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">text</p></body></html>"))
        self.proc_table.setTitle(_translate("MainWindow", "Proc Table"))
